spring:
  profiles:
    active: db
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${TRADE_USERNAME:trade.service.app@gmail.com}
    password: ${TRADE_GMAIL_PASS:sbimmaletiwxswin}
    file_type: ${TRADE_FILE_TYPE:application/vnd.ms-excel}
  default:
    redirect-url: ${FRONT_URL:http://localhost:3000}
    admin-url: ${ADMIN_URL:http://localhost:8080/admin/index}


scheduler:
  enable: ${ENABLE_SCHEDULERS:false}
  jobs:
    create-coupon: "0 0 * * * *" #Execute every hour